apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
resources:
- certificate.yaml
- ingressroute.yaml
patchesStrategicMerge:
  - configmap.yaml
  - service.yaml
  - deployment.yaml
patchesJson6902:
- target:
    version: v1
    kind: Service
    name: dashboard-svc
  path: service-patch.yaml
