apiVersion: v1
kind: Service
metadata:
  name: dashboard-svc
  labels:
    app: dashboard-svc
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "2112"
    prometheus.io/path: /metrics
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 8080
      protocol: TCP
  selector:
    app: dashboard-svc
