apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "2112"
    prometheus.io/scrape: "true"
  labels:
    app: robo-overview-service
  name: robo-overview-service
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: robo-overview-service
